basic_settings:
  site_title: "Between democracy and progress?"
  site_subtitle: Development, Nation Building and Education in Early Post-Colonial India (1930-1964)
  site_subtitle_2: 26th-28th October 2023
  site_place: Berlin
  site_description: "Explore India's educational evolution post-colonialism at the conference «Between Democracy and Progress». Join experts from history, economy, education, and political science fields to delve into the nation's educational development during 1930-1964. Understand its role in nation-building and how post-independence challenges shaped its landscape. We invite papers covering colonial rule's end to Nehru's developmental era."
  description: …
  edit_url: https://github.com/klickmeister/edit/main
  navigation:

